CREATE TABLE PRODUCTS (
  PRODUCTID INT PRIMARY KEY IDENTITY(1,1),
  PRODUCTNAME NVARCHAR(100) NOT NULL,
  PRICE DECIMAL(10, 2) NOT NULL,
  STOCK INT NOT NULL
);

-- Sample data
INSERT INTO PRODUCTS (PRODUCTNAME, PRICE, STOCK)
VALUES ('Pen', 1.25, 100), ('Notebook', 2.50, 50);
